spring:
    application:
        name: catalog-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/catalog-database

server:
    port: 8081

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka