spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_database?createDatabaseIfNotExist=true
    username: marouane
    password: Marouane@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # This should be set to 'update' to create or update tables automatically
    show-sql: true  # Optional: To log SQL statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    loadbalancer:
      ribbon:
        eureka:
          enabled: true
  webclient:
    base-url: http://catalog-service


server:
  port: 8082


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka